server:
  port: 8000

#spring:
#  application:
#    # 服务提供者的名称
#    name: dubbo-provider
#  cloud:
#    nacos:
#      discovery:
#        # 启动Nacos的地址
#        server-addr: 192.168.159.11:8848
#        # 在Nacos页面建的命名空间
#        namespace: a410bef9-5e1f-421d-8460-2e5ecea29c99
#      config:
#        server-addr: ${spring.cloud.nacos.discovery.server-addr}
#        group: provider
#        namespace: ${spring.cloud.nacos.discovery.namespace}
#        file-extension: yaml



dubbo:
  application:
    name: dubbo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://192.168.159.11:8848
    parameters:
      namespace: a410bef9-5e1f-421d-8460-2e5ecea29c99


